CFLAGS = 	-O1

SOURCE =	sys.c bugworld.c land.c pop.c comp.c breed.c
OBJECT =	sys.o bugworld.o land.o pop.o comp.o breed.o

CC =		gcc

bugworld:	$(OBJECT)
		$(CC) $(OBJECT) -o bugworld

clean:		;rm $(OBJECT)

# Do not delete
