/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: flex.skl,v 1.2 94/01/04 14:33:15 vern Exp $
 */

#define FLEX_SCANNER

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#ifdef __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */


#ifdef __TURBOC__
#define YY_USE_CONST
#endif


#ifndef YY_USE_CONST
#ifndef const
#define const
#endif
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.
 */
#define YY_START ((yy_start - 1) / 2)

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file".  Now included
 * only for backward compatibility with previous versions of flex.
 */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#ifdef __cplusplus
extern "C" {
#endif
	extern int yywrap YY_PROTO(( void ));
#ifdef __cplusplus
	}
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	/* Whether we've seen an EOF on this buffer. */
	int yy_eof_status;
#define EOF_NOT_SEEN 0
	/* "Pending" happens when the EOF has been seen but there's still
	 * some text to process.  Note that when we actually see the EOF,
	 * we switch the status back to "not seen" (via yyrestart()), so
	 * that the user can continue scanning by just pointing yyin at
	 * a new input file.
	 */
#define EOF_PENDING 1
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static void yyunput YY_PROTO(( int c, char *buf_ptr ));
void yyrestart YY_PROTO(( FILE *input_file ));
void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));

static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
static void yy_push_state YY_PROTO(( int new_state ));
static void yy_pop_state YY_PROTO(( void ));
static int yy_top_state YY_PROTO(( void ));

#ifndef yytext_ptr
static void yy_flex_strcpy YY_PROTO(( char *, const char * ));
#endif

static void *yy_flex_alloc YY_PROTO(( unsigned int ));
static void *yy_flex_realloc YY_PROTO(( void *ptr, unsigned int ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define INITIAL 0
typedef unsigned char YY_CHAR;
typedef int yy_state_type;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
extern char *yytext;
#define yytext_ptr yytext

#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( const char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = yy_cp - yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_END_OF_BUFFER 80
static const short int yy_accept[523] =
    {   0,
        0,    0,   80,   78,    1,    2,   78,    5,    3,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,    1,    5,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    6,    0,
        6,    0,    0,   43,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    4,    0,    0,    0,    0,    0,
       42,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   26,    0,    0,    0,    0,    0,    0,

        0,    0,   27,    0,    0,    0,    0,   28,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       47,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   29,    0,    9,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   30,    0,    0,    0,
        0,    0,    0,    7,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   44,   45,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   36,   37,    0,    0,    0,

        0,    0,    0,   40,   41,   38,   39,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   46,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   59,   11,    0,    8,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       34,    0,    0,    0,    0,    0,   35,    0,    0,   58,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   10,    0,    0,   60,   13,    0,    0,    0,    0,
       54,    0,   50,    0,   17,    0,   65,    0,    0,    0,
        0,    0,    0,    0,    0,   53,    0,   49,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   12,    0,    0,    0,   68,
        0,    0,    0,    0,    0,   33,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   48,    0,    0,    0,    0,

        0,    0,   63,    0,    0,    0,    0,   57,    0,    0,
       20,    0,   22,    0,   24,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   32,    0,
       75,   67,    0,    0,    0,    0,    0,   19,   21,   23,
       66,    0,   70,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   64,    0,    0,    0,    0,
       31,   71,    0,    0,    0,    0,    0,    0,    0,    0,
       56,   52,    0,    0,    0,    0,   55,   51,   61,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   18,    0,
        0,    0,    0,   16,    0,    0,    0,   14,    0,    0,

        0,   62,    0,   25,   76,    0,    0,    0,    0,    0,
        0,   15,    0,    0,   69,    0,    0,   77,   72,   74,
       73,    0
    } ;

static const int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    4,    1,    4,    5,    1,    6,    7,    8,
        9,    6,    6,    6,    6,    6,    6,   10,    1,    1,
        1,    1,    1,    1,   11,    1,   12,   13,   14,   15,
       16,   17,   18,   19,    1,   20,   21,   22,   23,   24,
        1,   25,   26,   27,   28,   29,   30,   31,   32,    1,
        1,    1,    1,    1,   33,    1,    1,    1,    1,    1,

       34,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const int yy_meta[35] =
    {   0,
        1,    1,    1,    1,    1,    2,    2,    2,    2,    1,
        1,    1,    1,    2,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2
    } ;

static const short int yy_base[524] =
    {   0,
        0,    0,  562,  563,  559,  563,   29,   34,  563,   31,
       34,   32,   36,   33,   40,  537,  536,  547,   49,  533,
       52,   31,  542,  530,  552,    0,   79,   85,  534,   44,
      528,   53,  526,   56,   74,  534,  534,  536,  523,  515,
       59,  522,  533,  516,  512,   25,  520,   70,   87,  515,
      511,  514,  514,  512,   60,  511,  516,  522,   82,   98,
      102,  499,  507,  563,  519,   91,  504,  504,  516,  503,
      511,  510,  499,  508,  563,  488,  500,  505,  498,  505,
      563,  492,  492,  500,  480,  479,  497,  496,  101,  484,
      496,  493,  481,  563,  492,  490,  485,  488,  487,  484,

      467,  478,  563,  485,  482,  475,  481,  563,  471,  465,
      469,  478,  469,  455,  109,  469,  473,  452,  457,  466,
      563,  457,  111,  113,  121,  448,  457,  461,  452,  459,
      462,  442,  441,  563,  448,  454,  446,  453,  117,  451,
      450,  445,  452,  119,  452,  431,  437,  435,  450,  116,
      447,  446,  446,  424,  435,  437,  421,  420,  439,  438,
      437,  436,  128,  563,  120,  425,  421,  432,  434,  431,
      417,  121,  428,  425,  407,  412,  563,  563,  412,  410,
      409,  408,  401,  400,  399,  418,  397,  403,  410,  413,
      394,  414,  406,  391,  408,  563,  563,  403,  406,  408,

      395,  390,  128,  563,  563,  563,  563,  393,  383,  400,
      388,  388,  378,  390,  376,  394,  384,  388,  393,  387,
      132,  121,  376,  370,  146,  387,  116,  132,  136,  382,
      373,  384,  374,  383,  362,  367,  367,  368,  373,  363,
      376,  361,  365,  354,  362,  366,  360,  359,  357,  362,
      366,  358,  361,  563,  364,  363,  351,  347,  345,  344,
      347,  351,  345,  354,  346,  563,  563,  158,  563,  332,
      349,  351,  347,  349,  345,  347,  332,  343,  344,  333,
      563,  341,  342,  325,  337,  334,  563,  333,  323,  563,
      323,  326,  334,  314,  318,  328,  325,  314,  328,  313,

      314,  309,  310,  310,  319,  318,  311,  319,  299,  295,
      309,  310,  310,  313,  308,  311,  306,  309,  295,  306,
      290,  563,  305,  282,  563,  563,  297,  299,  294,  297,
      563,  294,  563,  296,  563,  291,  563,  275,  295,  282,
      286,  290,  282,  288,  287,  563,  283,  563,  276,  271,
      271,  269,  274,  267,  272,  265,  270,  269,  261,  269,
      259,  146,  258,  258,  252,  563,  249,  248,  253,  563,
      255,  253,  254,  250,  264,  563,  241,  240,  249,  244,
      259,  255,  254,  253,  252,  251,  250,  252,  244,  238,
      249,  236,  244,  224,  223,  563,  139,  139,  222,  237,

      240,  230,  563,  219,  228,  151,  236,  563,  224,  220,
      563,  219,  563,  218,  563,  212,  220,  220,  208,  215,
      227,  152,  212,  214,  213,  221,  202,  207,  563,  206,
      563,  563,  208,  207,  206,  214,  210,  563,  563,  563,
      563,  204,  563,  143,  204,  197,  200,  208,  189,  206,
      199,  188,  205,  192,  201,  563,  201,  193,  182,  185,
      563,  563,  196,  177,  197,  189,  181,  193,  180,  191,
      563,  563,  175,  187,  188,  185,  563,  563,  563,  186,
      173,  169,  172,  173,  166,  178,  164,  172,  563,  162,
      162,  160,  172,  563,  163,  173,  165,  563,  164,  158,

      162,  563,  159,  563,  563,  148,  151,  150,  149,  126,
      114,  563,   80,   75,  563,   44,   40,  563,  563,  563,
      563,  563,   50
    } ;

static const short int yy_def[524] =
    {   0,
      522,    1,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,    8,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  523,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,

      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,

      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,

      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,

      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,

      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,    0,  522
    } ;

static const short int yy_nxt[598] =
    {   0,
        4,    5,    6,    7,    4,    8,    8,    8,    8,    9,
       10,   11,   12,   13,   14,   15,   16,    4,    4,   17,
       18,   19,    4,    4,    4,   20,   21,   22,    4,   23,
       24,    4,    4,    4,   26,   26,   26,   26,   27,   26,
       26,   26,   26,   29,   31,   34,   85,   28,   36,   35,
       40,   59,   55,   42,   56,   86,   32,   30,   37,   47,
       41,  521,   33,   38,   43,  520,   39,   28,   50,   63,
       64,   48,   97,   66,   51,   67,   69,   52,   79,   70,
       80,   53,   88,   54,   59,   59,   59,   59,   60,   98,
       61,   61,   61,   61,   71,   28,  519,   90,   72,   73,

       91,  518,   89,   61,   61,   61,   61,   61,   61,   61,
       61,  105,  127,  128,  106,   28,  151,  152,  159,  160,
      161,  162,  163,  177,  178,  183,  184,  185,  192,  163,
      164,  208,  217,  218,  264,  193,  517,  164,  271,  245,
      246,  272,  194,  261,  262,  195,  209,  268,  516,  210,
      424,  186,  247,  265,  273,  269,  263,  274,  275,  268,
      392,  276,  434,  425,  426,  427,  447,  269,  463,  464,
      515,  393,  514,  513,  512,  435,  511,  448,  449,  510,
      509,  508,  507,  506,  505,  504,  503,  502,  501,  500,
      499,  498,  497,  496,  495,  494,  493,  492,  491,  490,

      489,  488,  487,  486,  485,  484,  483,  482,  481,  480,
      479,  478,  477,  476,  475,  474,  473,  472,  471,  470,
      469,  468,  467,  466,  465,  462,  461,  460,  459,  458,
      457,  456,  455,  454,  453,  452,  451,  450,  446,  445,
      444,  443,  442,  441,  440,  439,  438,  437,  436,  433,
      432,  431,  430,  429,  428,  423,  422,  421,  420,  419,
      418,  417,  416,  415,  414,  413,  412,  411,  410,  409,
      408,  407,  406,  405,  404,  403,  402,  401,  400,  399,
      398,  397,  396,  395,  394,  391,  390,  389,  388,  387,
      386,  385,  384,  383,  382,  381,  380,  379,  378,  377,

      376,  375,  374,  373,  372,  371,  370,  369,  368,  367,
      366,  365,  364,  363,  362,  361,  360,  359,  358,  357,
      356,  355,  354,  353,  352,  351,  350,  349,  348,  347,
      346,  345,  344,  343,  342,  341,  340,  339,  338,  337,
      336,  335,  334,  333,  332,  331,  330,  329,  328,  327,
      326,  325,  324,  323,  322,  321,  320,  319,  318,  317,
      316,  315,  314,  313,  312,  311,  310,  309,  308,  307,
      306,  305,  304,  303,  302,  301,  300,  299,  298,  297,
      296,  295,  294,  293,  292,  291,  290,  289,  288,  287,
      286,  285,  284,  283,  282,  281,  280,  279,  278,  277,

      270,  267,  266,  260,  259,  258,  257,  256,  255,  254,
      253,  252,  251,  250,  249,  248,  244,  243,  242,  241,
      240,  239,  238,  237,  236,  235,  234,  233,  232,  231,
      230,  229,  228,  227,  226,  225,  224,  223,  222,  221,
      220,  219,  216,  215,  214,  213,  212,  211,  207,  206,
      205,  204,  203,  202,  201,  200,  199,  198,  197,  196,
      191,  190,  189,  188,  187,  182,  181,  180,  179,  176,
      175,  174,  173,  172,  171,  170,  169,  168,  167,  166,
      165,  158,  157,  156,  155,  154,  153,  150,  149,  148,
      147,  146,  145,  144,  143,  142,  141,  140,  139,  138,

      137,  136,  135,  134,  133,  132,  131,  130,  129,  126,
      125,  124,  123,  122,  121,  120,  119,  118,  117,  116,
      115,  114,  113,  112,  111,  110,  109,  108,  107,  104,
      103,  102,  101,  100,   99,   96,   95,   94,   93,   92,
       87,   84,   83,   82,   81,   78,   77,   76,   75,   74,
       68,   65,   62,   25,   58,   57,   49,   46,   45,   44,
       25,  522,    3,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522

    } ;

static const short int yy_chk[598] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    7,    7,    7,    7,    8,    8,
        8,    8,    8,   10,   11,   12,   46,    8,   13,   12,
       14,  523,   22,   15,   22,   46,   11,   10,   13,   19,
       14,  517,   11,   13,   15,  516,   13,    8,   21,   30,
       30,   19,   55,   32,   21,   32,   34,   21,   41,   34,
       41,   21,   48,   21,   27,   27,   27,   27,   28,   55,
       28,   28,   28,   28,   35,   59,  514,   49,   35,   35,

       49,  513,   48,   60,   60,   60,   60,   61,   61,   61,
       61,   66,   89,   89,   66,   59,  115,  115,  123,  123,
      124,  124,  125,  139,  139,  144,  144,  144,  150,  163,
      125,  165,  172,  172,  222,  150,  511,  163,  227,  203,
      203,  227,  150,  221,  221,  150,  165,  225,  510,  165,
      397,  144,  203,  222,  228,  225,  221,  228,  229,  268,
      362,  229,  406,  397,  398,  398,  422,  268,  444,  444,
      509,  362,  508,  507,  506,  406,  503,  422,  422,  501,
      500,  499,  497,  496,  495,  493,  492,  491,  490,  488,
      487,  486,  485,  484,  483,  482,  481,  480,  476,  475,

      474,  473,  470,  469,  468,  467,  466,  465,  464,  463,
      460,  459,  458,  457,  455,  454,  453,  452,  451,  450,
      449,  448,  447,  446,  445,  442,  437,  436,  435,  434,
      433,  430,  428,  427,  426,  425,  424,  423,  421,  420,
      419,  418,  417,  416,  414,  412,  410,  409,  407,  405,
      404,  402,  401,  400,  399,  395,  394,  393,  392,  391,
      390,  389,  388,  387,  386,  385,  384,  383,  382,  381,
      380,  379,  378,  377,  375,  374,  373,  372,  371,  369,
      368,  367,  365,  364,  363,  361,  360,  359,  358,  357,
      356,  355,  354,  353,  352,  351,  350,  349,  347,  345,

      344,  343,  342,  341,  340,  339,  338,  336,  334,  332,
      330,  329,  328,  327,  324,  323,  321,  320,  319,  318,
      317,  316,  315,  314,  313,  312,  311,  310,  309,  308,
      307,  306,  305,  304,  303,  302,  301,  300,  299,  298,
      297,  296,  295,  294,  293,  292,  291,  289,  288,  286,
      285,  284,  283,  282,  280,  279,  278,  277,  276,  275,
      274,  273,  272,  271,  270,  265,  264,  263,  262,  261,
      260,  259,  258,  257,  256,  255,  253,  252,  251,  250,
      249,  248,  247,  246,  245,  244,  243,  242,  241,  240,
      239,  238,  237,  236,  235,  234,  233,  232,  231,  230,

      226,  224,  223,  220,  219,  218,  217,  216,  215,  214,
      213,  212,  211,  210,  209,  208,  202,  201,  200,  199,
      198,  195,  194,  193,  192,  191,  190,  189,  188,  187,
      186,  185,  184,  183,  182,  181,  180,  179,  176,  175,
      174,  173,  171,  170,  169,  168,  167,  166,  162,  161,
      160,  159,  158,  157,  156,  155,  154,  153,  152,  151,
      149,  148,  147,  146,  145,  143,  142,  141,  140,  138,
      137,  136,  135,  133,  132,  131,  130,  129,  128,  127,
      126,  122,  120,  119,  118,  117,  116,  114,  113,  112,
      111,  110,  109,  107,  106,  105,  104,  102,  101,  100,

       99,   98,   97,   96,   95,   93,   92,   91,   90,   88,
       87,   86,   85,   84,   83,   82,   80,   79,   78,   77,
       76,   74,   73,   72,   71,   70,   69,   68,   67,   65,
       63,   62,   58,   57,   56,   54,   53,   52,   51,   50,
       47,   45,   44,   43,   42,   40,   39,   38,   37,   36,
       33,   31,   29,   25,   24,   23,   20,   18,   17,   16,
        5,    3,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
/* $Id: readscan.l,v 1.21 1994/05/01 10:38:48 holger Exp holger $ */
/* ========================================================================= */
/* (c) 1994 by Holger Totzke, Universitaet "Otto v. Guericke" Magdeburg      */
/* Diplomarbeit                                                              */
/* ------------------------------------------------------------------------- */
/* Dateiname : readscan.l                                                    */
/* Autor     : Holger Totzke                                                 */
/* Projekt   : PARATSP                                                       */
/* ========================================================================= */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "define.h"
#include "other.h"
#include "readpars.h"


extern long ParserLine;


char yystr[MAX_ZLEN];

#ifdef USE_PROTO
extern int read_line(char *s);
extern void read_string(void);
#else
extern int read_line();
extern void read_string();
#endif


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = getc( yyin ); \
		result = c == EOF ? 0 : 1; \
		buf[0] = (char) c; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;




	if ( yy_init )
		{
#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( yy_current_buffer )
			yy_init_buffer( yy_current_buffer, yyin );
		else
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();

		yy_init = 0;
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 523 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 563 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_USER_ACTION
/* Ueberlesen */
	YY_BREAK
case 2:
YY_USER_ACTION
{ ParserLine++;
                          return(yylval.kdo = Y_LF);
                        }
	YY_BREAK
case 3:
YY_USER_ACTION
return(yylval.kdo = Y_DP);
	YY_BREAK
case 4:
YY_USER_ACTION
return(yylval.kdo = Y_EOF);
	YY_BREAK
case 5:
YY_USER_ACTION
{ yylval.izahl = (int) atoi(yytext);
			  return(Y_IZAHL);
			}
	YY_BREAK
case 6:
YY_USER_ACTION
{ yylval.fzahl = (float) atof(yytext);
			  return(Y_FZAHL);
			}
	YY_BREAK
case 7:
YY_USER_ACTION
{ read_string();
			  return(Y_NAME_STR);
			}
	YY_BREAK
case 8:
YY_USER_ACTION
{ read_string();
			  return(Y_COMMENT_STR);
			}
	YY_BREAK
case 9:
YY_USER_ACTION
return(yylval.kdo = Y_TYPE);
	YY_BREAK
case 10:
YY_USER_ACTION
return(yylval.kdo = Y_DIMENSION);
	YY_BREAK
case 11:
YY_USER_ACTION
return(yylval.kdo = Y_CAPACITY);
	YY_BREAK
case 12:
YY_USER_ACTION
return(yylval.kdo = Y_GRAPH_TYPE);
	YY_BREAK
case 13:
YY_USER_ACTION
return(yylval.kdo = Y_EDGE_TYPE);
	YY_BREAK
case 14:
YY_USER_ACTION
return(yylval.kdo = Y_EDGE_WEIGHT_TYPE);
	YY_BREAK
case 15:
YY_USER_ACTION
return(yylval.kdo = Y_EDGE_WEIGHT_FORMAT);
	YY_BREAK
case 16:
YY_USER_ACTION
return(yylval.kdo = Y_EDGE_DATA_FORMAT);
	YY_BREAK
case 17:
YY_USER_ACTION
return(yylval.kdo = Y_NODE_TYPE);
	YY_BREAK
case 18:
YY_USER_ACTION
return(yylval.kdo = Y_NODE_COORD_TYPE);
	YY_BREAK
case 19:
YY_USER_ACTION
return(yylval.kdo = Y_COORD1_OFFSET);
	YY_BREAK
case 20:
YY_USER_ACTION
return(yylval.kdo = Y_COORD1_SCALE);
	YY_BREAK
case 21:
YY_USER_ACTION
return(yylval.kdo = Y_COORD2_OFFSET);
	YY_BREAK
case 22:
YY_USER_ACTION
return(yylval.kdo = Y_COORD2_SCALE);
	YY_BREAK
case 23:
YY_USER_ACTION
return(yylval.kdo = Y_COORD3_OFFSET);
	YY_BREAK
case 24:
YY_USER_ACTION
return(yylval.kdo = Y_COORD3_SCALE);
	YY_BREAK
case 25:
YY_USER_ACTION
return(yylval.kdo = Y_DISPLAY_DATA_TYPE);
	YY_BREAK
case 26:
YY_USER_ACTION
return(yylval.kdo = Y_TSP);
	YY_BREAK
case 27:
YY_USER_ACTION
return(yylval.kdo = Y_ATSP);
	YY_BREAK
case 28:
YY_USER_ACTION
return(yylval.kdo = Y_CVRP);
	YY_BREAK
case 29:
YY_USER_ACTION
return(yylval.kdo = Y_TOUR);
	YY_BREAK
case 30:
YY_USER_ACTION
return(yylval.kdo = Y_GRAPH);
	YY_BREAK
case 31:
YY_USER_ACTION
return(yylval.kdo = Y_COMPLETE_GRAPH);
	YY_BREAK
case 32:
YY_USER_ACTION
return(yylval.kdo = Y_SPARSE_GRAPH);
	YY_BREAK
case 33:
YY_USER_ACTION
return(yylval.kdo = Y_UNDIRECTED);
	YY_BREAK
case 34:
YY_USER_ACTION
return(yylval.kdo = Y_DIRECTED);
	YY_BREAK
case 35:
YY_USER_ACTION
return(yylval.kdo = Y_EXPLICIT);
	YY_BREAK
case 36:
YY_USER_ACTION
return(yylval.kdo = Y_EUC_2D);
	YY_BREAK
case 37:
YY_USER_ACTION
return(yylval.kdo = Y_EUC_3D);
	YY_BREAK
case 38:
YY_USER_ACTION
return(yylval.kdo = Y_MAX_2D);
	YY_BREAK
case 39:
YY_USER_ACTION
return(yylval.kdo = Y_MAX_3D);
	YY_BREAK
case 40:
YY_USER_ACTION
return(yylval.kdo = Y_MAN_2D);
	YY_BREAK
case 41:
YY_USER_ACTION
return(yylval.kdo = Y_MAN_3D);
	YY_BREAK
case 42:
YY_USER_ACTION
return(yylval.kdo = Y_GEO);
	YY_BREAK
case 43:
YY_USER_ACTION
return(yylval.kdo = Y_ATT);
	YY_BREAK
case 44:
YY_USER_ACTION
return(yylval.kdo = Y_XRAY1);
	YY_BREAK
case 45:
YY_USER_ACTION
return(yylval.kdo = Y_XRAY2);
	YY_BREAK
case 46:
YY_USER_ACTION
return(yylval.kdo = Y_SPECIAL);
	YY_BREAK
case 47:
YY_USER_ACTION
return(yylval.kdo = Y_HOTO);
	YY_BREAK
case 48:
YY_USER_ACTION
return(yylval.kdo = Y_FULL_MATRIX);
	YY_BREAK
case 49:
YY_USER_ACTION
return(yylval.kdo = Y_UPPER_ROW);
	YY_BREAK
case 50:
YY_USER_ACTION
return(yylval.kdo = Y_LOWER_ROW);
	YY_BREAK
case 51:
YY_USER_ACTION
return(yylval.kdo = Y_UPPER_DIAG_ROW);
	YY_BREAK
case 52:
YY_USER_ACTION
return(yylval.kdo = Y_LOWER_DIAG_ROW);
	YY_BREAK
case 53:
YY_USER_ACTION
return(yylval.kdo = Y_UPPER_COL);
	YY_BREAK
case 54:
YY_USER_ACTION
return(yylval.kdo = Y_LOWER_COL);
	YY_BREAK
case 55:
YY_USER_ACTION
return(yylval.kdo = Y_UPPER_DIAG_COL);
	YY_BREAK
case 56:
YY_USER_ACTION
return(yylval.kdo = Y_LOWER_DIAG_COL);
	YY_BREAK
case 57:
YY_USER_ACTION
return(yylval.kdo = Y_WEIGHT_LIST);
	YY_BREAK
case 58:
YY_USER_ACTION
return(yylval.kdo = Y_FUNCTION);
	YY_BREAK
case 59:
YY_USER_ACTION
return(yylval.kdo = Y_ADJ_LIST);
	YY_BREAK
case 60:
YY_USER_ACTION
return(yylval.kdo = Y_EDGE_LIST);
	YY_BREAK
case 61:
YY_USER_ACTION
return(yylval.kdo = Y_WEIGHTED_NODES);
	YY_BREAK
case 62:
YY_USER_ACTION
return(yylval.kdo = Y_UNWEIGHTED_NODES);
	YY_BREAK
case 63:
YY_USER_ACTION
return(yylval.kdo = Y_TWOD_COORDS);
	YY_BREAK
case 64:
YY_USER_ACTION
return(yylval.kdo = Y_THREED_COORDS);
	YY_BREAK
case 65:
YY_USER_ACTION
return(yylval.kdo = Y_NO_COORDS);
	YY_BREAK
case 66:
YY_USER_ACTION
return(yylval.kdo = Y_COORD_DISPLAY);
	YY_BREAK
case 67:
YY_USER_ACTION
return(yylval.kdo = Y_TWOD_DISPLAY);
	YY_BREAK
case 68:
YY_USER_ACTION
return(yylval.kdo = Y_NO_DISPLAY);
	YY_BREAK
case 69:
YY_USER_ACTION
return(yylval.kdo = Y_NODE_COORD_SECTION);
	YY_BREAK
case 70:
YY_USER_ACTION
return(yylval.kdo = Y_DEPOT_SECTION);
	YY_BREAK
case 71:
YY_USER_ACTION
return(yylval.kdo = Y_DEMAND_SECTION);
	YY_BREAK
case 72:
YY_USER_ACTION
return(yylval.kdo = Y_FIXED_EDGES_SECTION);
	YY_BREAK
case 73:
YY_USER_ACTION
return(yylval.kdo = Y_DISPLAY_DATA_SECTION);
	YY_BREAK
case 74:
YY_USER_ACTION
return(yylval.kdo = Y_NODE_WEIGHT_SECTION);
	YY_BREAK
case 75:
YY_USER_ACTION
return(yylval.kdo = Y_TOUR_SECTION);
	YY_BREAK
case 76:
YY_USER_ACTION
return(yylval.kdo = Y_EDGE_DATA_SECTION);
	YY_BREAK
case 77:
YY_USER_ACTION
return(yylval.kdo = Y_EDGE_WEIGHT_SECTION);
	YY_BREAK
case 78:
YY_USER_ACTION
return(yylval.kdo = Y_CHAR);
	YY_BREAK
case 79:
YY_USER_ACTION
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = yy_cp - yytext_ptr - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_input_file != yyin )
			{
			/* This can happen if we scan a file, yywrap() returns
			 * 1, and then later the user points yyin at a new
			 * file to resume scanning.  We have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input file.
			 */
			yy_current_buffer->yy_input_file = yyin;
			yy_n_chars = yy_current_buffer->yy_n_chars;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr - 1; /* copy prev. char, too */
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = yy_c_buf_p - yytext_ptr;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_eof_status != EOF_NOT_SEEN )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset = yy_c_buf_p - b->yy_ch_buf;

			b->yy_buf_size *= 2;
			b->yy_ch_buf = (char *)
				yy_flex_realloc( (void *) b->yy_ch_buf,
						 b->yy_buf_size );

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move - YY_MORE_ADJ == 1 )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_eof_status = EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	/* yytext begins at the second character in yy_ch_buf; the first
	 * character is the one which preceded it before reading in the latest
	 * buffer; it needs to be kept around in case it's a newline, so
	 * yy_get_previous_state() will have with '^' rules active.
	 */

	yytext_ptr = &yy_current_buffer->yy_ch_buf[1];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 523 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 523 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 522);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += dest - source;
		yy_bp += dest - source;
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
		yy_cp[-2] = '\n';

	*--yy_cp = (char) c;


	/* Note: the formal parameter *must* be called "yy_bp" for this
	 * macro to now work correctly.
	 */
	YY_DO_BEFORE_ACTION; /* set up yytext again */
	}


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *yy_c_buf_p;
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );

	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );

	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	yy_flex_free( (void *) b->yy_ch_buf );
	yy_flex_free( (void *) b );
	}


#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif
	{
	b->yy_input_file = file;

	/* We put in the '\n' and start reading from [1] so that an
	 * initial match-at-newline will be true.
	 */

	b->yy_ch_buf[0] = '\n';
	b->yy_n_chars = 1;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[1];

	b->yy_is_interactive = file ? isatty( fileno(file) ) : 0;

	b->yy_fill_buffer = 1;

	b->yy_eof_status = EOF_NOT_SEEN;
	}


#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		int new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}


static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}


static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}


#ifdef YY_USE_PROTOS
static void yy_fatal_error( const char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( 1 );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strcpy( char *s1, const char *s2 )
#else
static void yy_flex_strcpy( s1, s2 )
char *s1;
const char *s2;
#endif
	{
	while ( (*(s1++) = *(s2++)) )
		;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( unsigned int size )
#else
static void *yy_flex_alloc( size )
unsigned int size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, unsigned int size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
unsigned int size;
#endif
	{
	return (void *) realloc( ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}


int read_line(s)
  char *s;
{ int pos = 0;
  int ch;

  do
  { ch = input();
    yystr[pos++] = (char) ch;
  }
  while ((ch != '\n') && (ch != EOF));

  yystr[pos] = '\0';
  strcpy(s, yystr);
  ParserLine++;

  return((ch == EOF) ? 1 : 0);
}

void read_string()
{ int pos = 0;
  int ch;

  do
  { ch = input();
    yystr[pos++] = (char) ch;
  }
  while ((ch != '\n') && (ch != EOF));

  if (ch == '\n') unput('\n');
  yystr[--pos] = '\0';

  yylval.str = yystr;
}


/*** end of file ***/
